name : React CI
on : push
jobs :
  run-tests :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout Code
        uses : actions/checkout@v4
      - name : Use Noide.jobs
        uses : actions/setup-node@v3
        with :
            node-version : 18
      - name : Install Dependencies
        run : npm install

      - name : Run Test
        run : npm run test

